//! `brain setup claude-code|aider`: print the client configuration for a
//! profile, pointing the tool at OpenRouter directly (Phase 0). Nothing is
//! written to disk; the user pastes what they need.

use crate::config::Config;
use anyhow::Result;
use serde_json::json;

pub const OPENROUTER_ANTHROPIC_BASE: &str = "https://openrouter.ai/api";
pub const OPENROUTER_OPENAI_BASE: &str = "https://openrouter.ai/api/v1";

/// Where the tools' logs go so `brain events ingest` finds them.
pub fn data_dir() -> String {
    std::env::var("BRAIN_DATA").unwrap_or_else(|_| "$HOME/.local/share/llm_brain".into())
}

/// Env block for Claude Code. See docs/architecture/client-compatibility.md
/// for why each variable is there.
/// Claude Code's main model: the `agent` tier when configured, else `fast`.
pub fn claude_main_tier(cfg: &Config) -> &'static str {
    if cfg.model_for_tier("agent").is_ok() {
        "agent"
    } else {
        "fast"
    }
}

/// Shell function that runs the host's Claude Code through the llm_brain
/// proxy: main model = `brain/<agent tier>`, background tasks = `brain/fast`.
pub fn claude_code_proxy(cfg: &Config) -> Result<String> {
    let main = claude_main_tier(cfg);
    let _ = cfg.model_for_tier("fast")?;
    Ok(format!(
        "# Claude Code through the llm_brain proxy (dev profile). Paste into ~/.bashrc, run `px-claude` anywhere.\n\
         px-claude() {{\n\
           ANTHROPIC_BASE_URL=\"$BRAIN_BASE_URL\" ANTHROPIC_AUTH_TOKEN=\"$BRAIN_DEV_KEY\" \\\n\
           ANTHROPIC_MODEL=brain/{main} ANTHROPIC_DEFAULT_HAIKU_MODEL=brain/fast \\\n\
           CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1 CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=1 \\\n\
           claude \"$@\"\n\
         }}\n\
         # cheaper main model for simple sessions: ANTHROPIC_MODEL=brain/fast px-claude\n",
    ))
}

pub fn claude_code(cfg: &Config, profile: &str) -> Result<String> {
    let p = cfg.profile(profile)?;
    let fast = cfg.model_for_tier("fast")?;
    let key_env = p.key_env();
    Ok(format!(
        "# Claude Code → OpenRouter (profile `{profile}`, Phase 0). Add to your shell or ~/.claude/settings.json → env\n\
         export ANTHROPIC_BASE_URL={OPENROUTER_ANTHROPIC_BASE}\n\
         export ANTHROPIC_AUTH_TOKEN=\"${key_env}\"\n\
         export ANTHROPIC_MODEL={fast}\n\
         export ANTHROPIC_DEFAULT_HAIKU_MODEL={fast}\n\
         export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1\n\
         export CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=1\n\
         # switch tier in-session: /model {reasoning}\n",
        reasoning = cfg
            .model_for_tier("reasoning")
            .unwrap_or("<no reasoning tier>"),
    ))
}

/// Env block + `.aider.model.metadata.json` for aider (architect = reasoning, editor = fast).
pub fn aider(cfg: &Config, profile: &str) -> Result<(String, String)> {
    let p = cfg.profile(profile)?;
    let fast = cfg.model_for_tier("fast")?;
    let reasoning = cfg.model_for_tier("reasoning").unwrap_or(fast);
    let key_env = p.key_env();
    let env = format!(
        "# aider → OpenRouter (profile `{profile}`, Phase 0)\n\
         export OPENAI_API_BASE={OPENROUTER_OPENAI_BASE}\n\
         export OPENAI_API_KEY=\"${key_env}\"\n\
         # logs that `brain events ingest` reads (BRAIN_DATA)\n\
         mkdir -p {data}\n\
         # 90/10: editor = fast, architect = reasoning\n\
         aider --architect --model openai/{reasoning} --editor-model openai/{fast} --auto-test \\\n\
               --model-settings-file {data}/aider-model-settings.yml \\\n\
               --chat-history-file {data}/aider-chat.md --llm-history-file {data}/aider-llm.history\n",
        data = data_dir(),
    );
    let mut meta = serde_json::Map::new();
    for tier in ["fast", "reasoning"] {
        if let (Some(t), Ok(model)) = (cfg.tiers.get(tier), cfg.model_for_tier(tier)) {
            meta.insert(
                format!("openai/{model}"),
                json!({
                    "max_input_tokens": t.context,
                    "max_output_tokens": 32768,
                    "input_cost_per_token": t.input_usd_per_m / 1_000_000.0,
                    "output_cost_per_token": t.output_usd_per_m / 1_000_000.0,
                    "litellm_provider": "openai",
                    "mode": "chat"
                }),
            );
        }
    }
    Ok((
        env,
        serde_json::to_string_pretty(&serde_json::Value::Object(meta))?,
    ))
}

/// `.aider.model.settings.yml`: per-model `extra_body.models` so OpenRouter
/// falls back to the tier's fallback model on provider errors, rate limits
/// or downtime (billed by the model actually used). Needed because bonsai
/// has a single provider.
pub fn aider_model_settings(cfg: &Config) -> String {
    let mut out = String::from(
        "# generated by `brain setup aider` — edit formats and OpenRouter fallbacks per tier\n",
    );
    // aider assigns `whole` to models it doesn't know: whole-file rewrites,
    // expensive and fragile (a stray sentence becomes a file name). The fast
    // tier is the editor and gets the diff formats, as aider itself uses for
    // DeepSeek; the reasoning tier keeps aider's default as architect.
    // Entries exist for the concrete model ids (direct OpenRouter path) AND
    // for the `brain/<tier>` aliases (proxy path), because aider matches by name.
    for tier in ["fast", "reasoning"] {
        let Some(t) = cfg.tiers.get(tier) else {
            continue;
        };
        let Some(model) = t.model.as_deref() else {
            continue;
        };
        // In architect mode the *architect's* entry decides the editor format, so
        // the reasoning tier declares editor-diff too (its own replies stay text).
        let formats = if tier == "fast" {
            "  edit_format: diff\n  editor_edit_format: editor-diff\n  use_repo_map: true\n"
        } else {
            "  editor_edit_format: editor-diff\n  use_repo_map: true\n"
        };
        let mut chain = vec![model.to_string()];
        if let Some(fb) = t.fallback.as_deref() {
            chain.push(fb.to_string());
        }
        let list = chain
            .iter()
            .map(|m| format!("\"{m}\""))
            .collect::<Vec<_>>()
            .join(", ");
        // direct path: fallback chain goes in the request body
        out.push_str(&format!(
            "- name: openai/{model}\n{formats}  extra_params:\n    extra_body:\n      models: [{list}]\n"
        ));
        // proxy path: the proxy resolves the alias and adds the fallbacks itself
        out.push_str(&format!("- name: openai/brain/{tier}\n{formats}"));
    }
    out
}

/// The rules aider loads with `--read` on every session (its CLAUDE.md).
pub const AIDER_CONVENTIONS: &str = "\
# Working rules for aider (loaded every session)

- Work in small, complete steps: implement, run the tests, then stop and report.
- Touch only the files needed for the task; never reformat or reorganize unrelated code.
- Code, comments and commit messages in English. Conventional commits: `type(scope): summary`.
- Never commit secrets, `.env` files or credentials. Never edit generated files by hand.
- Before changing behaviour, read the existing tests for that area; add or update tests with the change.
- If the request is ambiguous, ask one precise question instead of guessing; otherwise do not ask for confirmation.
- Prefer editing existing files over creating new ones. No new dependencies without saying why.
- When a command or test fails, show the relevant lines and fix the cause, not the symptom.
- At the end of each task, list the files changed and what a reviewer should look at.
- You have no tools here: reply in plain text and code blocks only; never emit `<tool_call>`, `<function=…>` or JSON tool-call markup. To change a file, describe the edit or show the new content.
";

/// aider flags that make it behave like a headless-friendly agent: no
/// confirmations, architect proposals applied, commits on, diffs shown,
/// history restored per repo, conventions loaded. Shared by the host,
/// Docker and proxy functions.
pub fn aider_agent_flags(data: &str) -> String {
    format!(
        "--yes-always --auto-accept-architect --auto-commits --show-diffs --restore-chat-history \\\n\
         --no-suggest-shell-commands --no-check-update --no-show-model-warnings --notifications \\\n\
         --read {data}/aider-conventions.md"
    )
}

/// Shell function that runs aider through the llm_brain proxy: `BRAIN_BASE_URL`
/// and `BRAIN_DEV_KEY` come from the git-ignored local env file. Chat history
/// stays per repo (`.aider.chat.history.md`) so `--restore-chat-history`
/// resumes the right conversation; `brain events ingest` scans the repos.
pub fn aider_proxy(cfg: &Config) -> Result<String> {
    let _ = cfg.model_for_tier("fast")?;
    let data = data_dir();
    Ok(format!(
        "# aider through the llm_brain proxy. Paste into ~/.bashrc (after sourcing deploy/server.local.env), run `px-aider` inside a git repo.\n\
         px-aider() {{\n\
           OPENAI_API_BASE=\"$BRAIN_BASE_URL/v1\" OPENAI_API_KEY=\"$BRAIN_DEV_KEY\" \\\n\
           aider --architect --model openai/brain/reasoning --editor-model openai/brain/fast \\\n\
             --model-metadata-file {data}/aider-model-metadata.json \\\n\
             --model-settings-file {data}/aider-model-settings.yml \\\n\
             --llm-history-file {data}/aider-llm.history \\\n\
             {flags} \\\n\
             $([ -f CLAUDE.md ] && echo --read CLAUDE.md) \"$@\"\n\
         }}\n",
        flags = aider_agent_flags(&data),
    ))
}

/// Shell function that runs Claude Code from a Docker image: current repo
/// mounted, a persistent HOME under `BRAIN_DATA/claude-home` so sessions,
/// settings and trust survive (and `brain events ingest` reads them), same
/// variables as [`claude_code`].
pub fn claude_code_docker(cfg: &Config, profile: &str, image: &str) -> Result<String> {
    let p = cfg.profile(profile)?;
    let fast = cfg.model_for_tier("fast")?;
    let reasoning = cfg
        .model_for_tier("reasoning")
        .unwrap_or("<no reasoning tier>");
    let key_env = p.key_env();
    let data = data_dir();
    Ok(format!(
        "# Claude Code from Docker → OpenRouter (profile `{profile}`). Paste into ~/.bashrc, then run `or-claude` inside a git repo.\n\
         # Sessions land in {data}/claude-home/.claude/projects (ingested by `brain events ingest`).\n\
         or-claude() {{\n\
           mkdir -p {data}/claude-home\n\
           docker run --rm -it --user \"$(id -u):$(id -g)\" -e HOME={data}/claude-home \\\n\
             -v \"$PWD:$PWD\" -w \"$PWD\" -v \"{data}/claude-home:{data}/claude-home\" \\\n\
             -e ANTHROPIC_BASE_URL={OPENROUTER_ANTHROPIC_BASE} -e ANTHROPIC_AUTH_TOKEN=\"${key_env}\" \\\n\
             -e ANTHROPIC_MODEL={fast} -e ANTHROPIC_DEFAULT_HAIKU_MODEL={fast} \\\n\
             -e CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1 -e CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=1 \\\n\
             {image} claude \"$@\"\n\
         }}\n\
         # switch tier in-session: /model {reasoning}\n",
    ))
}

/// Shell function that runs aider from the Docker image with the current
/// repo mounted, for machines where aider is not installed. Same model
/// split and log files as [`aider`], so `brain events ingest` sees it.
pub fn aider_docker(cfg: &Config, profile: &str, image: &str) -> Result<String> {
    let p = cfg.profile(profile)?;
    let fast = cfg.model_for_tier("fast")?;
    let reasoning = cfg.model_for_tier("reasoning").unwrap_or(fast);
    let key_env = p.key_env();
    let data = data_dir();
    Ok(format!(
        "# aider from Docker → OpenRouter (profile `{profile}`). Paste into ~/.bashrc, then run `or-aider` inside a git repo.\n\
         # Save the metadata JSON from `brain setup aider` as {data}/aider-model-metadata.json for cost display.\n\
         or-aider() {{\n\
           mkdir -p {data}\n\
           docker run --rm -it --user \"$(id -u):$(id -g)\" -e HOME=/tmp \\\n\
             -v \"$PWD:$PWD\" -w \"$PWD\" -v \"{data}:{data}\" \\\n\
             -e OPENAI_API_BASE={OPENROUTER_OPENAI_BASE} -e OPENAI_API_KEY=\"${key_env}\" \\\n\
             {image} aider --architect --model openai/{reasoning} --editor-model openai/{fast} \\\n\
               --no-check-update --no-analytics \\\n\
               --model-metadata-file {data}/aider-model-metadata.json \\\n\
               --model-settings-file {data}/aider-model-settings.yml \\\n\
               --chat-history-file {data}/aider-chat.md --llm-history-file {data}/aider-llm.history \"$@\"\n\
         }}\n",
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> Config {
        Config::from_yaml(
            "profiles:\n  - {name: dev, tier: fast, daily_limit_usd: 3.0, monthly_soft_usd: 30.0}\n",
            "tiers:\n  fast: {model: prism-ml/ternary-bonsai-2-27b, context: 262144, input_usd_per_m: 0.075, output_usd_per_m: 0.5}\n  reasoning: {model: deepseek/deepseek-v4-pro, context: 1048576, input_usd_per_m: 0.42, output_usd_per_m: 0.84}\n",
        )
        .unwrap()
    }

    #[test]
    fn claude_code_block_points_at_openrouter_with_the_profile_key() {
        let out = claude_code(&cfg(), "dev").unwrap();
        assert!(out.contains("ANTHROPIC_BASE_URL=https://openrouter.ai/api\n"));
        assert!(out.contains("ANTHROPIC_AUTH_TOKEN=\"$OPENROUTER_KEY_DEV\""));
        assert!(out.contains("ANTHROPIC_MODEL=prism-ml/ternary-bonsai-2-27b"));
        assert!(out.contains("CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=1"));
        assert!(out.contains("/model deepseek/deepseek-v4-pro"));
        assert!(claude_code(&cfg(), "nope").is_err());
    }

    #[test]
    fn claude_proxy_function_uses_the_agent_tier_for_the_main_model() {
        let out = claude_code_proxy(&cfg()).unwrap();
        assert!(
            out.contains("ANTHROPIC_MODEL=brain/fast ANTHROPIC_DEFAULT_HAIKU_MODEL=brain/fast"),
            "no agent tier in this config: {out}"
        );
        let with_agent = Config::from_yaml(
            "profiles:\n  - {name: dev, tier: fast, daily_limit_usd: 3.0, monthly_soft_usd: 30.0}\n",
            "tiers:\n  fast: {model: f}\n  agent: {model: deepseek/deepseek-v4-pro}\n",
        )
        .unwrap();
        let out = claude_code_proxy(&with_agent).unwrap();
        assert!(
            out.contains("ANTHROPIC_MODEL=brain/agent ANTHROPIC_DEFAULT_HAIKU_MODEL=brain/fast"),
            "{out}"
        );
        assert!(out.contains("ANTHROPIC_AUTH_TOKEN=\"$BRAIN_DEV_KEY\""));
    }

    #[test]
    fn claude_docker_function_mounts_repo_and_persistent_home() {
        let out = claude_code_docker(&cfg(), "dev", "llm-brain-claude-test:latest").unwrap();
        assert!(out.contains("or-claude() {"));
        assert!(
            out.contains("-e HOME=$HOME/.local/share/llm_brain/claude-home"),
            "{out}"
        );
        assert!(out.contains("-v \"$PWD:$PWD\" -w \"$PWD\""), "{out}");
        assert!(
            out.contains("-e ANTHROPIC_AUTH_TOKEN=\"$OPENROUTER_KEY_DEV\""),
            "{out}"
        );
        assert!(
            out.contains("-e ANTHROPIC_MODEL=prism-ml/ternary-bonsai-2-27b"),
            "{out}"
        );
        assert!(
            out.contains("-e CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=1"),
            "{out}"
        );
        assert!(
            out.contains("llm-brain-claude-test:latest claude \"$@\""),
            "{out}"
        );
        assert!(claude_code_docker(&cfg(), "nope", "x").is_err());
    }

    #[test]
    fn aider_model_settings_chain_primary_and_fallback_per_tier() {
        let cfg2 = Config::from_yaml(
            "profiles:\n  - {name: dev, tier: fast, daily_limit_usd: 3.0, monthly_soft_usd: 30.0}\n",
            "tiers:\n  fast: {model: deepseek/deepseek-v4-flash, fallback: qwen/qwen3.7-flash}\n  reasoning: {model: prism-ml/ternary-bonsai-2-27b, fallback: deepseek/deepseek-v4-pro}\n",
        )
        .unwrap();
        let y = aider_model_settings(&cfg2);
        assert!(
            y.contains("- name: openai/prism-ml/ternary-bonsai-2-27b"),
            "{y}"
        );
        assert!(
            y.contains("models: [\"prism-ml/ternary-bonsai-2-27b\", \"deepseek/deepseek-v4-pro\"]"),
            "{y}"
        );
        assert!(
            y.contains("models: [\"deepseek/deepseek-v4-flash\", \"qwen/qwen3.7-flash\"]"),
            "{y}"
        );
        // fast tier = editor → diff formats; reasoning tier keeps aider's default
        assert!(y.contains("- name: openai/deepseek/deepseek-v4-flash\n  edit_format: diff\n  editor_edit_format: editor-diff\n"), "{y}");
        assert!(
            !y.contains("- name: openai/prism-ml/ternary-bonsai-2-27b\n  edit_format"),
            "{y}"
        );
        assert!(
            serde_yaml::from_str::<serde_yaml::Value>(&y).is_ok(),
            "valid YAML"
        );
        // no fallback configured → single-element chain
        let y1 = aider_model_settings(&cfg());
        assert!(
            y1.contains("models: [\"prism-ml/ternary-bonsai-2-27b\"]"),
            "{y1}"
        );
    }

    #[test]
    fn aider_proxy_function_is_agent_like() {
        let out = aider_proxy(&cfg()).unwrap();
        assert!(out.contains("px-aider() {"));
        assert!(
            out.contains(
                "OPENAI_API_BASE=\"$BRAIN_BASE_URL/v1\" OPENAI_API_KEY=\"$BRAIN_DEV_KEY\""
            ),
            "{out}"
        );
        assert!(
            out.contains("--model openai/brain/reasoning --editor-model openai/brain/fast"),
            "{out}"
        );
        for flag in [
            "--yes-always",
            "--auto-accept-architect",
            "--auto-commits",
            "--show-diffs",
            "--restore-chat-history",
            "--no-suggest-shell-commands",
            "--read $HOME/.local/share/llm_brain/aider-conventions.md",
        ] {
            assert!(out.contains(flag), "missing {flag}: {out}");
        }
        assert!(
            !out.contains("--chat-history-file"),
            "history stays per repo for restore"
        );
        assert!(AIDER_CONVENTIONS.contains("Conventional commits"));
    }

    #[test]
    fn aider_docker_function_mounts_repo_and_logs_with_the_dev_key() {
        let out = aider_docker(&cfg(), "dev", "llm-brain-aider-test:latest").unwrap();
        assert!(out.contains("or-aider() {"));
        assert!(out.contains("-v \"$PWD:$PWD\" -w \"$PWD\""), "{out}");
        assert!(
            out.contains("-e OPENAI_API_KEY=\"$OPENROUTER_KEY_DEV\""),
            "{out}"
        );
        assert!(out.contains("llm-brain-aider-test:latest aider --architect --model openai/deepseek/deepseek-v4-pro --editor-model openai/prism-ml/ternary-bonsai-2-27b"), "{out}");
        assert!(
            out.contains("--chat-history-file $HOME/.local/share/llm_brain/aider-chat.md"),
            "{out}"
        );
        assert!(
            out.contains(
                "--model-metadata-file $HOME/.local/share/llm_brain/aider-model-metadata.json"
            ),
            "{out}"
        );
        assert!(
            out.contains(
                "--model-settings-file $HOME/.local/share/llm_brain/aider-model-settings.yml"
            ),
            "{out}"
        );
    }

    #[test]
    fn aider_block_uses_architect_editor_split_and_prices_metadata() {
        let (env, meta) = aider(&cfg(), "dev").unwrap();
        assert!(env.contains("OPENAI_API_BASE=https://openrouter.ai/api/v1"));
        assert!(env.contains("--model openai/deepseek/deepseek-v4-pro --editor-model openai/prism-ml/ternary-bonsai-2-27b"));
        assert!(
            env.contains("--chat-history-file $HOME/.local/share/llm_brain/aider-chat.md"),
            "{env}"
        );
        let v: serde_json::Value = serde_json::from_str(&meta).unwrap();
        let fast = &v["openai/prism-ml/ternary-bonsai-2-27b"];
        assert_eq!(fast["max_input_tokens"], 262144);
        assert!((fast["input_cost_per_token"].as_f64().unwrap() - 0.075e-6).abs() < 1e-12);
        assert!(v.get("openai/deepseek/deepseek-v4-pro").is_some());
    }
}
